/* XPM */
static char * hyperbola_m_xpm[] = {
"32 32 109 2",
"  	c #FFFFFF",
". 	c #CBCBCB",
"+ 	c #7F7F7F",
"@ 	c #3F3F3F",
"# 	c #121212",
"$ 	c #989898",
"% 	c #343434",
"& 	c #B9B9B9",
"* 	c #EDEDED",
"= 	c #FCFCFC",
"- 	c #E6EAE8",
"; 	c #B4B7B4",
"> 	c #F6F6F6",
", 	c #F6FAF7",
"' 	c #E9F5EC",
") 	c #DBEDE0",
"! 	c #CDE3D4",
"~ 	c #8A918D",
"{ 	c #F6FBF7",
"] 	c #EAF5EC",
"^ 	c #DBEDDF",
"/ 	c #CAE5D2",
"( 	c #B8DDC1",
"_ 	c #B3D4BA",
": 	c #EAF4EC",
"< 	c #B9DCC1",
"[ 	c #A6D4B1",
"} 	c #93CBA1",
"| 	c #96A89B",
"1 	c #DBEEE0",
"2 	c #CAE5D1",
"3 	c #A6D3B1",
"4 	c #82C292",
"5 	c #93C19F",
"6 	c #CBE6D1",
"7 	c #B9DDC2",
"8 	c #93CBA2",
"9 	c #71BA83",
"0 	c #70B883",
"a 	c #CAE6D1",
"b 	c #B8DCC2",
"c 	c #A6D3B2",
"d 	c #71BA84",
"e 	c #63B277",
"f 	c #66B379",
"g 	c #E9F4ED",
"h 	c #A6D4B2",
"i 	c #71B984",
"j 	c #62B277",
"k 	c #56AD6C",
"l 	c #7CB68A",
"m 	c #959595",
"n 	c #CDCDCD",
"o 	c #DAEEE0",
"p 	c #B8DCC1",
"q 	c #94CAA2",
"r 	c #72BA83",
"s 	c #63B377",
"t 	c #57AC6C",
"u 	c #4DA864",
"v 	c #86A18D",
"w 	c #000000",
"x 	c #0E0E0E",
"y 	c #5A5A5A",
"z 	c #888888",
"A 	c #CFE3D4",
"B 	c #B8DDC2",
"C 	c #94CBA2",
"D 	c #72B983",
"E 	c #70B582",
"F 	c #ABABAB",
"G 	c #010101",
"H 	c #3D3D3D",
"I 	c #757B77",
"J 	c #B3D5BC",
"K 	c #82C192",
"L 	c #72BA84",
"M 	c #76877B",
"N 	c #7A7A7A",
"O 	c #666666",
"P 	c #323232",
"Q 	c #252525",
"R 	c #96A89A",
"S 	c #93C1A0",
"T 	c #71B883",
"U 	c #65B479",
"V 	c #6C6C6C",
"W 	c #3E3E3E",
"X 	c #F1F1F1",
"Y 	c #A5A5A5",
"Z 	c #545454",
"` 	c #2C2C2C",
" .	c #606060",
"..	c #9A9A9A",
"+.	c #373737",
"@.	c #FEFEFE",
"#.	c #999999",
"$.	c #333333",
"%.	c #565656",
"&.	c #A9A9A9",
"*.	c #A1A1A1",
"=.	c #5E5E5E",
"-.	c #5B5B5B",
";.	c #A4A4A4",
">.	c #DADADA",
",.	c #040404",
"'.	c #C1C1C1",
").	c #B6B6B6",
"!.	c #CCCCCC",
"                                                                ",
"                                                                ",
"                                                                ",
"                        . + @ # # @ + .                         ",
"                      $ % & * = = - ; % $                       ",
"                    $ $ >       , ' ) ! ~ $                     ",
"                  . % >       { ] ^ / ( _ % .                   ",
"                  + &       { : ^ / < [ } | +                   ",
"                  @ *     { ] 1 2 < 3 } 4 5 @                   ",
"                  # =   , : ^ 6 7 3 8 4 9 0 #                   ",
"                  # = , ' ^ a b c 8 4 d e f #                   ",
"                  @ - g ) 2 < h } 4 i j k l @                   ",
"            m n   + ; o 2 p c q 4 r s t u v +     n m           ",
"            w x y z % A B [ C 4 D e k u E % . F y x w           ",
"            w w w G H I J q K L j k u E M N O G w w w           ",
"            P w w w w Q Q R S T U l v % V W w w w w P           ",
"            X Y Z w w w `  .@ # # @ + ..+.w w w Z Y X           ",
"                @.#.$.w w %.X       X %.w w $.#.@.              ",
"                    &.x w w *.      *.w w x &.                  ",
"                      =.w w -.      -.w w =.                    ",
"                      ;.w w Q       Q w w ;.                    ",
"                      >.w w ,.      ,.w w >.                    ",
"                      ;.w w Q       Q w w ;.                    ",
"                      =.w w -.      -.w w =.                    ",
"                    &.x w w *.      *.w w x &.                  ",
"                @.#.$.w w %.X       X %.w w $.#.@.              ",
"            X Y Z w w w +.'.          '.+.w w w Z Y X           ",
"            P w w w w W ).              ).W w w w w P           ",
"            w w w G O !.                  !.O G w w w           ",
"            w x y F                           F y x w           ",
"            m n                                   n m           ",
"                                                                "};
